services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./kafka-ui/application.yml:/etc/kafkaui/application.yml:ro
      - ./certs:/certs:ro
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: /etc/kafkaui/application.yml
