spring:
  ssl:
    bundle:
      jks:
        kafka:
          truststore:
            location: ${KAFKA_TRUSTSTORE_LOCATION}
            password: ${KAFKA_TRUSTSTORE_PASSWORD}
            type: JKS
          keystore:
            location: ${KAFKA_KEYSTORE_LOCATION}
            password: ${KAFKA_KEYSTORE_PASSWORD}
            type: JKS
            key-password: ${KAFKA_KEY_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    ssl:
      bundle: kafka
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${SCHEMA_REGISTRY_USERNAME}:${SCHEMA_REGISTRY_PASSWORD}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
