package com.example.demo.core;

public enum GilErrorCode {
  // --- Core/Engine configuration & flow/rules/transformations ---
  CORE_CONFIG_MISSING,
  CORE_CONFIG_INVALID,
  CORE_CONFIG_SCHEMA_INVALID,
  CORE_CONFIG_VERSION_UNSUPPORTED,
  CORE_FLOW_VALIDATION_FAILED,
  CORE_FLOW_EXECUTION_FAILED,
  CORE_STEP_EXECUTION_FAILED,
  CORE_MAPPING_FAILED,
  CORE_RULE_EVALUATION_FAILED,
  TRANSFORMATION_DEFINITION_INVALID,
  TRANSFORMATION_EXECUTION_ERROR,
  REGU_CONFIG_MISSING,
  REGU_CONFIG_INVALID,

  UNKNOWN
}