auth:
  type: disabled

kafka:
  clusters:
    - name: local-es-duplicate
      bootstrapServers: "broker1:19093,broker2:19093,broker3:19093"

      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: >
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="token"
          password="local-token";

        ssl.truststore.location: /certs/kafka.truststore.jks
        ssl.truststore.password: truststore-password
        ssl.truststore.type: JKS

        ssl.keystore.location: /certs/client.keystore.jks
        ssl.keystore.password: changeit
        ssl.key.password: changeit
        ssl.keystore.type: JKS

      schemaRegistry: "https://schema-registry:8085"
      schemaRegistryAuth:
        username: token
        password: local-sr-password